spring.application.name=supplierpulse

spring.datasource.url=jdbc:postgresql://localhost:5432/supplierpulse
spring.datasource.username=postgres
spring.datasource.password=samavi15

spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false
